### ISSUE TITLE
Ability to add more ROS packages to the rosification

### ISSUE THREAD

**Issue by alikureishy** [rickstaa/.ros_conda_wrapper#12]
**Is your feature request related to a problem? Please describe.**
Seems like only certain ROS packages are included.

**Describe the solution you'd like**
Would be nice to be able to include additional ROS packages for installation into the wrapped environment via some configuration change. For example, "gazebo_msgs" is presently not included in the installation, and I'd like to include that. Furthermore, if I want to create custom ros packages, I'd like to be able to add those python packages to the wrapped environment too.

**Describe alternatives you've considered**

**Additional context**

**Comment by rickstaa** [comment]
Hey @safdark thanks a lot for your issue. I currently use `conda-forge` to install the main ROS packages (see line 22 of the [ros_conda_wrapper](https://github.com/rickstaa/.ros_conda_wrapper/blob/7d2940a58f2a2cf72f05588bd3b9b3dba5048d70/ros_conda_wrapper_rc)). These conda-forge packages are created by [Wolf Vollprecht](https://medium.com/@wolfv/ros-on-conda-forge-dca6827ac4b6) and some other ROS community members to make ROS packages available on Conda (you can follow [this gitter](https://gitter.im/RoboStack/Lobby#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications) to keep up to date with the project). 

I will add the essential ROS packages that became available after my last release to the `ROS_CONDA_FORGE_DEP`. Additionally, I could add an extra `-p` flag after the `rosinit` command so that people can supply provide other non-essential ROS packages like `gazebo` to be installed during the initialization. Is that what you had in mind or were you thinking of another mechanism?

**Comment by rickstaa** [comment]
I checked this feature request and it would require some code restructuring to have the ability to supply additional packages with the conda Rosification command. Additionally I currently do not think this feature would be very usefull as you can just use the `conda install` command to install additional packages. The `init` command only installs the bare minimum of packages in order to be able to use ROS inside a Conda environment.
