### ISSUE TITLE
can ros_conda_wrapper work with conda installed outside the home directory?

### ISSUE THREAD

**Issue by libphy** [rickstaa/.ros_conda_wrapper#13]
I have a machine that has conda installed in a shared directory e.g. /opt.
After running ros_conda_wrapper installation script, I tested if the --ros-wrapper after a normal conda activcate command would work with my existing conda environment which is located in opt/anaconda3/envs. 
For example, when I run this command `conda activate tf22 --ros-wrapper`, I expect that the environment tf22 will work with ros. Instead I got an error message:
```
activate does not accept more than one argument:                                                                                                                              ['tf22', '--ros-wrapper'] 
```
I'm not sure if this occurs because my conda home directory in not my user home directory (I've followed the same instruction as in this github repo's README page- the .ros_conda_wrapper directory isn under $HOME dir). Can someone verify if the installation script also works with the similar case (when the conda is installed some other place than the $HOME directory)? In order to make this work, what changes do I need to make?

**Comment by rickstaa** [comment]
@libphy Thanks a lot for your interest in the Ros Conda Wrapper. The behaviour you are experiencing is as intended as I by design did not fully overload the Conda `activate` command. As a result, the activation and deactivation are done by Conda. The `--ros-wrapper` can be accessed by using the following syntax `conda --ros-wrapper`. I updated the README.md with some code examples to make it more clear. Let me know if that solves your problem.

**Comment by rickstaa** [comment]
@libphy Closed due to inactivity.
