### ISSUE TITLE
Add deprication warning to the repository as RoboStack released native ROS conda packages

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/.ros_conda_wrapper#18]
As stated by @Tobias-Fischer in https://github.com/ros/ros/issues/149 this package should not be needed anymore now, it is possible to install ROS packages directly (natively) in a Conda environment using https://github.com/RoboStack/ros-noetic & https://medium.com/robostack/cross-platform-conda-packages-for-ros-fa1974fd1de3 🚀 . This will result in a very minimal wrapper that only unsets the PYTHONPATH. I will test out which versions don't require the wrapper anymore, create a new small wrapper and put a deprecation warning for which the original wrapper is not needed anymore.

**Comment by Tobias-Fischer** [comment]
Hi @rickstaa,
Many thanks for actioning this! I would recommend a slightly different approach. How about leaving the (code) contents of this repository as is? It could still be an alternative (yet deprecated) way of using ROS+conda. While the Robostack packages are working fine for us, they are not (yet) officially supported and experimental. And while we have built the most popular packages, some packages might still be missing there.

Re the `PYTHONPATH`: we can take care of this directly in the conda activation scripts so that end-users don't have to rely on another wrapper - I have opened an issue: https://github.com/RoboStack/ros-noetic/issues/54 - it would be great if you become a contributor in RoboStack :)

/cc @wolfv @traversaro

**Comment by rickstaa** [comment]
@Tobias-Fischer, I think your approach is the right one. I will update the README a bit to explain the use cases for which the wrapper is still used. Thanks for opening RoboStack/ros-noetic#54. I think it will improve the user experience. I'm also happy to become a contributor to RoboStack. I have been on [the gitter](https://gitter.im/RoboStack/Lobby) for some months now but haven't come across a bug yet or a not implemented package. I am, however, happy to send a pull request tot he https://github.com/RoboStack repository might I encounter anything in the future.

**Comment by rickstaa** [comment]
A small message redirecting users to the RoboStack has been added in [v1.0.7](https://github.com/rickstaa/.ros_conda_wrapper/releases/tag/v1.0.7).

**Comment by Tobias-Fischer** [comment]
Many thanks @rickstaa
